### PR TITLE
Added cookies

### PR DESCRIPTION
**Pull request by nilesh05apr**
When trying to get attachments/files from attachment url the request was blocked.
To solve this added cookies to the get request as attachments_arguments.
    attachment_args = {
        'timeout': 20,
        'headers': {
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) '
                        'Chrome/46.0.2490.86 Safari/537.36',
            'Referer':
            'https://erp.iitkgp.ac.in/SSOAdministration/login.htm?sessionToken=595794DC220159D1CBD10DB69832EF7E.worker3',
            'cookie':'JSESSIONID=198C7AA25A2206AA75C4CA212ECD4DCB.worker3; ssoToken=%s; JSID#/IIT_ERP3=2C7F12F1FB8E280086A5C1AFE79EAC67.worker2; JSID#/Academic=F1F80C4EEEB75B9D7B40D97FA46A9515.worker2; JSID#/ERPAccounts=502825F974872A8A03B0B4AAFA7A14DD.worker1; JSID#/TrainingPlacementSSO=198C7AA25A2206AA75C4CA212ECD4DCB.worker3'% ssoToken
        },
        'verify': False
    }

  r = session.get(notice['attachment_url'], stream=True,**attachment_args)

### CODE REVIEW

**Comment by thealphadollar** [comment]
Hey @nilesh05apr thanks for the PR.

This PR has many more changes - like migration to Python 3 - than just adding cookies. Also, you've hardcoded the cookies - which will expire after sometime as each login gets a separate cookie.

In this program, we are using sessions and logginn into ERP - so these cookies are already part of the request that we make for retrieving the attachment and need not be specified separately (especially not in a hardcoded fashion).

I'll suggest - let's raise a PR to migrate to Python3 first and then we can fix the attachments issue. What do you think?

**Comment by nilesh05apr** [comment]
Sure, I am working on migration. I will let you know when i am done. After that we can work on attachment issue.
Thank you for the suggestion.

**Comment by nilesh05apr** [comment]
@thealphadollar i have migrated the code from python2 to python3 and tested it on python 3.8.2 on linux ubuntu 20.04 machine.
Please review the code.

**Comment by proffapt** [comment]
Closing this PR, because:

- https://github.com/metakgp/mftp/pull/62
- The code is migrated to current latest version of python.
- `session` is used for ERP navigation. Already has the required cookies, and it works..

**Pull request closed without merging**
