### PR TITLE
This will fix the problem with wierd attachments

### PR DESCRIPTION
**Pull request by iakshat**

### CODE REVIEW

**Review by thealphadollar — APPROVED** [review]
Thanks a lot @iakshat for promptly making the fix. You are way faster than we could be. :sparkles: :sparkles:

**Comment by thealphadollar** [comment]
@iakshat We would absolutely love to enjoy your company and learn more from you. Can you please grace us with your presence in our slack group?

PS. get your exclusive invite at slack.metakgp.org :heart_eyes:

**Comment by iakshat** [comment]
Thank you for the invite, I'm already added to the slack group. Really appreciate your warm encouragement! I'd love to be a part of other metakgp projects!

**Comment by thealphadollar** [comment]
Oh, I'm so sorry @iakshat . I was so excited to have you with us, I missed checking the channel. I'm so happy you are already a part of the group ☺️

**Comment by amrav** [comment]
Thanks for fixing this issue!

I noticed this change means the pdf will always be named "attachment.pdf".
Sometimes the name of the pdf has information in it, eg
"selected_students_round_2.pdf", it would be nice to preserve this in the
emails. You could do it by using python's url parsing library to extract
the last part of the attachment_url, discarding the query params. Up to you
:)

**Comment by iakshat** [comment]
@amrav Yes I actually thought about that but the ERP servers all the notices from a common URL and they just differ in URL parameter id. So even if we try to extract the last part of the URL, they will all be named the same except the id (actually the previous system implemented that). We can actually name the files with some combination of company name and subject if you want.

**Comment by amrav** [comment]
Interesting, if the parameters have some information then another option is
to construct the filename by joining the parameters together, but if
they're just opaque ids then the current approach seems fine.

**Pull request merged**
