### PR TITLE
added Dockerfile

### LINKED ISSUE #59: Dockerise
Dockerise the codebase in for easy deployment.

### PR DESCRIPTION
**Pull request by LakshyaSatpal**
fixes #59

### CODE REVIEW

**Comment by LakshyaSatpal** [comment]
@proffapt Hey, can you review this please?

**Review by proffapt — COMMENTED** [review]
Now that I think of it, I don't think dockerising it is needed now.. since it has now become a service.. also it's not a single option thingy.. you have smtp.. gmail api.. then you might run it as a daemon or a cronjob ¯\_(ツ)_/¯

**Comment by LakshyaSatpal** [comment]
Umm, yep, that also makes sense :)
So, should we close this issue for now?

**Comment by proffapt** [comment]
I mean, I guess so? What do you say? Docker is mostly used for two things in such small projects:
- Getting dependencies setup
- Starting the damn thing ¯\_(ツ)_/¯ 

But since it can be used as a service and dependenices well are just one command away and the setup requires human intervention.. like:
- Token files for login
- Token file for sending mail
- configuring what you want to use.. smtp or api 
And idk here and there..

so I guess docker is not what we need.. I don't know much docker but not needed either I believe ?

**Comment by LakshyaSatpal** [comment]
Okay, it makes sense that the environment setup is mostly manual which can't be automated. 
I think the best what we can do about this is, to expect environment variables and build the image using them. So, the user won't be copying and creating the `env.py`. But, I believe this won't reduce much effort for a normal user. 

Docker will only help here for containerized deployment. Even if we add it as an enhancement, it will stay unused, since deploying such a small project on a container doesn't make sense.

Overall, my vote is to drop this issue. Still, if easy deployment is priority for you I can work on this, won't take much time.

**Comment by proffapt** [comment]
let's talk over slack

**Comment by proffapt** [comment]
Not needed at this stage.. closing the issue and pr

**Pull request closed without merging**
